chore: add npm metadata
crabnebula-dev/file-icons pull request #13
Opened 2023-11-08 09:47 UTC by CrabNejonas

Adds metadata for npm

2023-11-08 14:05 UTC, lucasfernog-crabnebula requested changes

2023-11-08 14:05 UTC, lucasfernog-crabnebula commented on Cargo.toml
>  version = "0.1.0"
```suggestion
version = "0.0.0"
```

2023-11-08 14:05 UTC, lucasfernog-crabnebula commented on .changes/metadata.md
> +Update manifest metadata
```suggestion
---
"file-icons": minor
---

Initial release.
```

2023-11-08 21:05 UTC, lucasfernog-crabnebula commented
Btw when we merge this one, we need to have the crate ready to be published otherwise we'll be stuck for NPM releases.

2023-11-09 08:27 UTC, CrabNejonas commented
> Btw when we merge this one, we need to have the crate ready to be published otherwise we'll be stuck for NPM releases.

yeah let's close this and focus on the npm changes

2023-11-09 08:27 UTC, closed without merging

2023-11-09 08:40 UTC, CrabNejonas commented
superseded by #15